"""Yield to Maturity (YTM) calculation via numerical root-finding.

Pure-Python solver (no numpy/scipy): Newton-Raphson with a bisection
fallback on ``[-0.5, 2.0]``.

Discounting uses exact fractional periods on the ACT/365 day-count
convention: each future payment is discounted by the actual number of
calendar days from the valuation date to the payment date,

    pv = sum over payments of
             amount / (1 + r / periods_per_year) ** (days * periods_per_year / 365)

so a coupon that is one day away is discounted by (1 + r/ppy)^(ppy/365),
not by a whole coupon period. This matches the ACT/365-style convention of
the accrued coupon (НКД) module (actual days over a 365/182/91-day year).
"""

from __future__ import annotations

import logging
import math
from datetime import date

from bond_accounting.yield_calc.coupon_schedule import _add_months

logger = logging.getLogger(__name__)

_FREQUENCY_MONTHS: dict[str, int] = {
    "ANNUAL": 12,
    "SEMI_ANNUAL": 6,
    "QUARTERLY": 3,
}
_PERIODS_PER_YEAR: dict[str, int] = {
    "ANNUAL": 1,
    "SEMI_ANNUAL": 2,
    "QUARTERLY": 4,
}

#: Convergence tolerance on the pricing function value.
_TOLERANCE = 1e-8
#: Maximum Newton-Raphson iterations.
_MAX_ITERATIONS = 100
#: Bisection bracket for the annual YTM (as a fraction).
_BISECTION_LOW = -0.5
_BISECTION_HIGH = 2.0
#: Day-count denominator for the ACT/365 convention (fractional discounting).
_DAYS_PER_YEAR = 365
#: Hard inclusive lower bound on the ``price`` argument, in currency units per bond.
#: A sub-unit price is a data-entry error regardless of nominal.
_PRICE_MIN = 1.0
#: Upper bound on ``price`` as a multiple of the bond's nominal (face value).
#: Legitimate bond trading prices stay within a few multiples of face value;
#: 10x is a loose data-validity guard, not a market assumption. Scaling by
#: nominal keeps the bound consistent with ``BondCreate.nominal`` (which has
#: no upper bound), so a par-priced bond is always accepted.
_PRICE_MAX_NOMINAL_MULTIPLE = 10.0


def _price_bounds(nominal: int) -> tuple[float, float]:
    """Inclusive valid range for ``price``, in currency units per bond.

    The upper bound scales with ``nominal`` so that par-priced bonds are
    accepted for any positive nominal.
    """
    return _PRICE_MIN, _PRICE_MAX_NOMINAL_MULTIPLE * nominal


class YtmCalculationError(Exception):
    """Raised for invalid inputs to YTM calculation."""


def _future_payment_dates(maturity_date: date, months: int, today: date) -> list[date]:
    """Return future coupon dates (chronological), ending with maturity.

    Coupon dates are generated by stepping one period back from
    ``maturity_date`` while the date is strictly after ``today``.
    """
    dates: list[date] = []
    current = maturity_date
    while current > today:
        dates.append(current)
        current = _add_months(current, -months)
    dates.reverse()
    return dates


def _cash_flows(
    maturity_date: date, months: int, today: date, coupon: float, nominal: int
) -> list[tuple[int, float]]:
    """Future cash flows as ``(days_from_today, amount)`` pairs.

    Each coupon is a standalone payment; the final payment (at maturity)
    additionally includes the nominal. Days are actual calendar days
    (ACT/365 convention).
    """
    dates = _future_payment_dates(maturity_date, months, today)
    return [
        ((payment_date - today).days, coupon + (nominal if payment_date == maturity_date else 0.0))
        for payment_date in dates
    ]


def _present_value(
    r: float,
    cash_flows: list[tuple[int, float]],
    periods_per_year: int,
) -> float:
    """Discounted value of all future payments at annual rate ``r`` (fraction).

    Each payment is discounted by the exact fractional number of periods
    since the valuation date, ACT/365:

        amount / (1 + r / periods_per_year) ** (days * periods_per_year / 365)
    """
    factor = 1.0 + r / periods_per_year
    pv = 0.0
    for days, amount in cash_flows:
        pv += amount / factor ** (days * periods_per_year / _DAYS_PER_YEAR)
    return pv


def _present_value_derivative(
    r: float,
    cash_flows: list[tuple[int, float]],
    periods_per_year: int,
) -> float:
    """Derivative of :func:`_present_value` with respect to ``r``."""
    factor = 1.0 + r / periods_per_year
    derivative = 0.0
    for days, amount in cash_flows:
        periods = days * periods_per_year / _DAYS_PER_YEAR
        derivative += -amount * periods / (periods_per_year * factor ** (periods + 1))
    return derivative


def _bisect(
    price: float,
    cash_flows: list[tuple[int, float]],
    periods_per_year: int,
) -> float | None:
    """Find YTM by bisection on the ``[-0.5, 2.0]`` bracket.

    Returns None if the pricing function does not change sign over the
    bracket (i.e. no root exists within the bounds).
    """

    def f(r: float) -> float:
        return _present_value(r, cash_flows, periods_per_year) - price

    low, high = _BISECTION_LOW, _BISECTION_HIGH
    f_low, f_high = f(low), f(high)
    if f_low * f_high > 0:
        logger.warning(
            "YTM bisection: no sign change on [%s, %s] (f(lo)=%.6g, f(hi)=%.6g)",
            low,
            high,
            f_low,
            f_high,
        )
        return None

    for _ in range(200):
        mid = (low + high) / 2
        f_mid = f(mid)
        if abs(f_mid) < _TOLERANCE or high - low < 1e-12:
            return mid
        if f_low * f_mid < 0:
            high, f_high = mid, f_mid
        else:
            low, f_low = mid, f_mid
    return (low + high) / 2


def calculate_ytm(
    price: float,
    coupon_rate: float,
    coupon_frequency: str,
    maturity_date: date,
    nominal: int = 1000,
    today: date | None = None,
) -> float | None:
    """Calculate Yield to Maturity via Newton-Raphson (fallback: bisection).

    Solves for the annualized rate ``r`` (fraction, e.g. ``0.05`` = 5%) that
    equates the discounted future coupon and principal payments to ``price``:

        price = sum over future payments of
                    amount / (1 + r / periods_per_year) ** (days * periods_per_year / 365)

    Discounting uses exact fractional periods on the ACT/365 day-count
    convention: ``days`` is the actual number of calendar days from the
    valuation date to the payment date, so a coupon that is one day away
    is discounted by a fraction of a period rather than a whole period.
    ``periods_per_year`` is derived from the coupon frequency (ANNUAL = 1,
    SEMI_ANNUAL = 2, QUARTERLY = 4), as in the rest of the module.

    Day-count and price conventions:

    - Day count: ACT/365 (actual days, 365-day year), consistent with the
      accrued coupon (НКД) module which uses the same ACT/365-style basis
      (actual days over fixed 365/182/91-day period lengths).
    - ``price`` is the full (dirty) price per bond in currency units: the
      present value of all future cash flows. If the caller holds a clean
      price, the accrued coupon (НКД) must be added before calling, since
      the fractional discounting applies to each actual payment date.

    Args:
        price: Current full (dirty) price per bond in currency units
            (e.g. ``1020`` for 102% of a nominal of 1000). Must be within
            ``[1, 10 * nominal]`` inclusive. The upper bound is relative to
            the nominal because ``nominal`` itself is unbounded: a par bond
            with ``nominal > 999`` is a valid instrument. 10x face value is a
            loose data-validity guard, not a market assumption.
        coupon_rate: Annual coupon rate in percent.
        coupon_frequency: One of ``ANNUAL``, ``SEMI_ANNUAL``, ``QUARTERLY``.
        maturity_date: Bond maturity date.
        nominal: Nominal (face) value per bond unit.
        today: Valuation date; defaults to ``date.today()``.

    Returns:
        Annualized YTM as a fraction, or None if no root exists within the
        solver bounds ``[-0.5, 2.0]``.

    Raises:
        YtmCalculationError: If inputs are invalid (price outside the bounds
            ``[1, 10 * nominal]`` currency units, unknown frequency, negative
            coupon rate, non-positive nominal, or maturity on or before the
            valuation date).
    """
    valuation_date = today if today is not None else date.today()

    frequency = coupon_frequency.upper()
    months = _FREQUENCY_MONTHS.get(frequency)
    if months is None:
        raise YtmCalculationError(
            f"Unsupported coupon frequency {coupon_frequency!r}; expected one of {sorted(_FREQUENCY_MONTHS)}"
        )
    if coupon_rate < 0:
        raise YtmCalculationError(f"coupon_rate must be non-negative, got {coupon_rate}")
    if nominal <= 0:
        raise YtmCalculationError(f"nominal must be positive, got {nominal}")
    price_min, price_max = _price_bounds(nominal)
    if not price_min <= price <= price_max:
        raise YtmCalculationError(
            f"price must be within [{price_min:g}, {price_max:g}] currency units per bond "
            f"({_PRICE_MAX_NOMINAL_MULTIPLE:g}x nominal={nominal}), got {price}"
        )
    if maturity_date <= valuation_date:
        raise YtmCalculationError(
            f"maturity_date {maturity_date} must be after valuation date {valuation_date}"
        )

    periods_per_year = _PERIODS_PER_YEAR[frequency]
    days_to_maturity = (maturity_date - valuation_date).days
    years_to_maturity = days_to_maturity / _DAYS_PER_YEAR
    coupon = nominal * coupon_rate / 100 / periods_per_year

    # Zero-coupon bond: closed-form solution.
    if coupon == 0.0:
        # price = nominal / (1 + r / ppy) ** (days * ppy / 365)
        ytm = periods_per_year * (
            (nominal / price) ** (_DAYS_PER_YEAR / (days_to_maturity * periods_per_year)) - 1
        )
        logger.debug("Zero-coupon YTM: %.8f (days=%d)", ytm, days_to_maturity)
        return ytm

    cash_flows = _cash_flows(maturity_date, months, valuation_date, coupon, nominal)

    def f(r: float) -> float:
        return _present_value(r, cash_flows, periods_per_year) - price

    # Newton-Raphson with the standard "total yield" initial guess.
    annual_coupon = nominal * coupon_rate / 100
    guess = (annual_coupon + (nominal - price) / years_to_maturity) / ((nominal + price) / 2)
    # Keep the starting point inside the valid domain and bracket.
    guess = min(max(guess, _BISECTION_LOW), 1.0)

    r = guess
    for _ in range(_MAX_ITERATIONS):
        f_value = f(r)
        if abs(f_value) < _TOLERANCE:
            logger.debug("YTM converged via Newton-Raphson: r=%.8f", r)
            return r
        derivative = _present_value_derivative(r, cash_flows, periods_per_year)
        if derivative == 0.0 or not math.isfinite(derivative):
            break
        r_next = r - f_value / derivative
        if not math.isfinite(r_next) or r_next < _BISECTION_LOW or abs(r_next) > 1.0:
            logger.debug(
                "Newton-Raphson diverged (r=%.6g -> r_next=%.6g); falling back to bisection",
                r,
                r_next,
            )
            break
        if r_next == r:
            # No further progress; try bisection for the last word.
            break
        r = r_next

    result = _bisect(price, cash_flows, periods_per_year)
    if result is None:
        logger.warning(
            "YTM did not converge: price=%.4f, coupon_rate=%.2f, maturity=%s",
            price,
            coupon_rate,
            maturity_date,
        )
    else:
        logger.debug("YTM converged via bisection: r=%.8f", result)
    return result
