"""initial tables: users, bonds, transactions

Revision ID: 0001
Revises:
Create Date: 2026-09-20

Creates the three core tables (``users``, ``bonds``, ``transactions``) with
their uniqueness and CHECK constraints. Works on both SQLite and PostgreSQL:
``sa.Identity()`` renders ``GENERATED BY DEFAULT AS IDENTITY`` on PostgreSQL
and is ignored by SQLite (plain ``INTEGER PRIMARY KEY`` autoincrement).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "bonds",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("nominal", sa.Integer(), nullable=False),
        sa.Column("coupon_rate", sa.Float(), nullable=False),
        sa.Column("coupon_frequency", sa.String(length=20), nullable=False),
        sa.Column("maturity_date", sa.Date(), nullable=False),
        sa.Column("issuer", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isin"),
        sa.CheckConstraint(
            "coupon_frequency IN ('ANNUAL', 'SEMI_ANNUAL', 'QUARTERLY')",
            name="ck_bonds_coupon_frequency",
        ),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("bond_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("commission", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["bond_id"], ["bonds.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("type IN ('BUY', 'SELL', 'MATURE')", name="ck_transactions_type"),
    )


def downgrade() -> None:
    op.drop_table("transactions")
    op.drop_table("bonds")
    op.drop_table("users")
