"""initial tables: users, brokers, bonds, broker_accounts, transactions

Revision ID: 0001
Create Date: 2026-09-21

Single consolidated migration (replaces the former 0001–0003 chain) that
creates the full schema: ``users``, ``brokers``, ``bonds``,
``broker_accounts`` and ``transactions`` with their uniqueness, foreign key
and CHECK constraints. Works on both SQLite and PostgreSQL:
``sa.Identity()`` renders ``GENERATED BY DEFAULT AS IDENTITY`` on PostgreSQL
and is ignored by SQLite (plain ``INTEGER PRIMARY KEY`` autoincrement).

Notes on column semantics:

* ``bonds.owner_id`` — NOT NULL FK → ``users.id`` (indexed); every bond
  belongs to exactly one user.
* ``bonds.nominal`` — NOT NULL with DB-level ``DEFAULT 1000`` so rows
  inserted outside the ORM (raw SQL, other clients) also get 1000 when the
  column is omitted, matching ``BondCreate.nominal``.
* ``broker_accounts.account_type`` — restricted to ``STANDARD`` / ``IIS`` /
  ``LTD`` by a CHECK constraint.
* ``transactions.broker_account_id`` — NOT NULL FK → ``broker_accounts.id``
  (indexed); every transaction is executed on a broker account.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "brokers",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("commission", sa.Float(), nullable=False),
        sa.Column("min_commission", sa.Float(), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "bonds",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("nominal", sa.Integer(), server_default="1000", nullable=False),
        sa.Column("coupon_rate", sa.Float(), nullable=False),
        sa.Column("coupon_frequency", sa.String(length=20), nullable=False),
        sa.Column("maturity_date", sa.Date(), nullable=False),
        sa.Column("issuer", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"]),
        sa.UniqueConstraint("isin"),
        sa.CheckConstraint(
            "coupon_frequency IN ('ANNUAL', 'SEMI_ANNUAL', 'QUARTERLY')",
            name="ck_bonds_coupon_frequency",
        ),
    )
    op.create_index("ix_bonds_owner_id", "bonds", ["owner_id"])
    op.create_table(
        "broker_accounts",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("broker_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("account_number", sa.String(length=100), nullable=True),
        sa.Column("account_type", sa.String(length=20), nullable=False),
        sa.Column("opened_at", sa.Date(), nullable=True),
        sa.Column("closed_at", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["broker_id"], ["brokers.id"]),
        sa.CheckConstraint(
            "account_type IN ('STANDARD', 'IIS', 'LTD')",
            name="ck_broker_accounts_type",
        ),
    )
    op.create_index("ix_broker_accounts_user_id", "broker_accounts", ["user_id"])
    op.create_index("ix_broker_accounts_broker_id", "broker_accounts", ["broker_id"])
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("bond_id", sa.Integer(), nullable=False),
        sa.Column("broker_account_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("commission", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["bond_id"], ["bonds.id"]),
        sa.ForeignKeyConstraint(["broker_account_id"], ["broker_accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("type IN ('BUY', 'SELL', 'MATURE')", name="ck_transactions_type"),
    )
    op.create_index("ix_transactions_broker_account_id", "transactions", ["broker_account_id"])


def downgrade() -> None:
    op.drop_table("transactions")
    op.drop_table("broker_accounts")
    op.drop_table("bonds")
    op.drop_table("brokers")
    op.drop_table("users")
