"""add account operations table and brokers.min_commission_type

Revision ID: 0002
Create Date: 2026-09-21

Creates the ``account_operations`` table (non-trading money movements on a
broker account) and adds ``brokers.min_commission_type`` with a CHECK
constraint. Works on both SQLite and PostgreSQL:

* ``sa.Identity()`` renders ``GENERATED BY DEFAULT AS IDENTITY`` on PostgreSQL
  and is ignored by SQLite (plain ``INTEGER PRIMARY KEY`` autoincrement).
* The ``brokers`` change uses ``batch_alter_table``: on SQLite the table is
  recreated (SQLite cannot ``ALTER TABLE ... ADD CONSTRAINT``), on PostgreSQL
  a regular ``ALTER TABLE`` is issued.

Notes on column semantics:

* ``account_operations.type`` — restricted to ``DEPOSIT`` / ``WITHDRAWAL`` /
  ``TAX`` by a CHECK constraint.
* ``account_operations.amount`` — positivity is enforced at the API/service
  layer (Pydantic), not by the database.
* ``brokers.min_commission_type`` — NOT NULL with DB-level ``DEFAULT
  'PERCENT'`` so existing rows get 'PERCENT' when the column is added, and
  rows inserted outside the ORM (raw SQL, other clients) also get 'PERCENT'
  when the column is omitted (same pattern as ``bonds.nominal``).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "account_operations",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("broker_account_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["broker_account_id"], ["broker_accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "type IN ('DEPOSIT', 'WITHDRAWAL', 'TAX')",
            name="ck_account_operations_type",
        ),
    )
    op.create_index("ix_account_operations_user_id", "account_operations", ["user_id"])
    op.create_index(
        "ix_account_operations_broker_account_id",
        "account_operations",
        ["broker_account_id"],
    )
    with op.batch_alter_table("brokers") as batch_op:
        batch_op.add_column(
            sa.Column(
                "min_commission_type",
                sa.String(length=10),
                server_default="PERCENT",
                nullable=False,
            )
        )
        batch_op.create_check_constraint(
            "ck_brokers_min_commission_type",
            "min_commission_type IN ('PERCENT', 'RUBLES')",
        )


def downgrade() -> None:
    with op.batch_alter_table("brokers") as batch_op:
        batch_op.drop_constraint("ck_brokers_min_commission_type", type_="check")
        batch_op.drop_column("min_commission_type")
    op.drop_index("ix_account_operations_broker_account_id", table_name="account_operations")
    op.drop_index("ix_account_operations_user_id", table_name="account_operations")
    op.drop_table("account_operations")
